### ISSUE TITLE
Support the RPKI Repository Delta Protocol (RFC8182)

### ISSUE THREAD

**Issue by timbru** [NICMx/FORT-validator#20]
Hi,

Do you have plans to support the RPKI Repository Delta Protocol (RRDP)?
https://tools.ietf.org/html/rfc8182

This is an additional protocol that was invented in response to issues with rsync (which I will not repeat here for brevity). It has seen quite some deployment both in publishers and validators. As you may have seen I started a discussion in the IETF sidrops WG about deprecating rsync altogether and moving to RRDP.

Fort is one of two remaining validators, that I know of, which do not support RRDP. So, it would be really great if you are open to adding this. And greater still if you, or I as your proxy, could report those plans to the IETF.

**Comment by pcarana** [comment]
Hi there Tim,

Yes. As a matter of fact, we're currently implementing RRDP support. Same as #19, this will be released during the first months of the next year.

> And greater still if you, or I as your proxy, could report those plans to the IETF.
Well, why not both? We really appreciate your aid as a proxy, so that the WG and any other interested person/entity will know that RRDP support is currently on our development roadmap.

Thanks for getting in touch. We'll keep this issue open until RRDP support is implemented and released.

**Comment by pcarana** [comment]
Released with [v1.2.0](https://github.com/NICMx/FORT-validator/releases/tag/v1.2.0) :+1:
